##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.grafana:6.3.5 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/run.sh"
COPY ./conteco/configs/etc/grafana/grafana.ini /etc/grafana/grafana.ini
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="grafana" \
    CONTECO_NAME="base" \
    CONTECO_TAG="6.3.5" \
    CONTECO_BASE="external.grafana:6.3.5" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="grafana" \
      io.vcweb.name="base" \
      io.vcweb.tag="6.3.5" \
      io.vcweb.base="external.grafana:6.3.5" \
      io.vcweb.build="image-base" \
      io.vcweb.label="grafana.base - ContEco" \
      io.vcweb.description="Grafana Base image, with minor configuration change." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.grafana.base --help" 
##### END image.base/Dockerfile/env-labels-footer #####
