##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="grafana" \
    CONTECO_NAME="base" \
    CONTECO_TAG="7.2.1" \
    CONTECO_BASE="external.grafana:7.2.1" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="grafana" \
      io.vcweb.name="base" \
      io.vcweb.tag="7.2.1" \
      io.vcweb.base="external.grafana:7.2.1" \
      io.vcweb.build="image-base" \
      io.vcweb.label="grafana.base - ContEco" \
      io.vcweb.description="Grafana Base image, with minor configuration change." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.grafana.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
