#!/usr/bin/env bash

export CONTECO_LABEL="Conteco grafana base"
export CONTECO_DESCRIPTION="The ContEco Grafana base image."

export CONTECO_TYPE="grafana"
export CONTECO_NAME="base"
export CONTECO_TAG="6.3.5"

export CONTECO_BASE="external.grafana:6.3.5"
export CONTECO_BUILD="image-base"
