# # config file version
apiVersion: 1
  
datasources:
- name: metricbeat_docker_container
  type: elasticsearch
  access: proxy
  orgId: 1
  url: http://elasticsearch:9200
  database: "infometis_metricbeat_docker_container_ymd*"
  isDefault: false
  jsonData:
    esVersion: 6.0
    interval: 
    timeField: "@timestamp"
    timeInterval: 60s
  version: 1
  editable: true   
  